"""
Practice Test 1:    | 
Letzte WIEDERHOLUNG: Q160 | 
Besondere Fragen Udemy   | 122


-------------------
Practice Test 2: ✅ | 100%

-------------------
Practice Test 3: ✅ | 76% | 93%

-------------------
Practice Test 4: ✅ | 83%

-------------------
Practice Test 5: ✅ | 83%

-------------------
Practice Test 6: ✅ | 70%

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
"""


"""

Q246

What is the best definition of a script?



It's an error message generated by the interpreter

Richtige Antwort
It's a text file that contains instructions which make up a Python program

It's a text file that contains sequences of zeroes and ones

It's an error message generated by the compiler
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Q454

A way of passing arguments in which the order of the arguments

determines the initial parameter's values is referred to as:?



ordered

Richtige Antwort
positional

sequential
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 126
Übersprungen
Q140

isalnum() checks if a string contains only letters and digits, and this is:



A module
Erklärung
The isalnum() method is not a module in Python. Modules in Python are files containing Python code that can define functions, classes, and variables. The isalnum() method is specifically a string method used for checking alphanumeric characters within a string.

A function
Erklärung
The isalnum() function is not a standalone function in Python; it is a method that belongs to the string class. Functions in Python are standalone blocks of code that can be called independently, whereas methods are functions that are associated with an object and are called using dot notation on that object.

Richtige Antwort
A method

Erklärung
The isalnum() method is a built-in method in Python that belongs to the string class. It is used to check if a string contains only alphanumeric characters (letters and digits). As a method, it is called on a string object using dot notation, such as "string.isalnum()".
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 127
Übersprungen
Q126

The 0o prefix means that the number after it is denoted as:



hexadecimal

Richtige Antwort
octal

binary

decimal
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 129
Übersprungen
Q441

Which of the following enclose the input parameters or arguments of a function?



Quotation marks

Brackets

Curly braces

Richtige Antwort
Parentheses
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 132
Übersprungen
Q457

Select the true statements:



(Select two answers)



Richtige Auswahl
You cannot use keywords as function names in Python

You can use keywords as function names in Python

You can use keywords as variable names in Python

Richtige Auswahl
You cannot use keywords as variable names in Python
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 136
Übersprungen
Q446

What do you call a command-line interpreter which lets you interact

with your OS and execute Python commands and scripts?



Jython

Erklärung
Jython is not the correct choice in this context. Jython is an implementation of Python that runs on the Java platform, allowing Python code to interact with Java libraries. It is not a command-line interpreter that lets users interact with the OS and execute Python commands and scripts. Jython is a specific implementation of Python, not a general-purpose command-line interpreter.

Richtige Antwort
A console

Erklärung
A console is the correct choice because it refers to a command-line interpreter that allows users to interact with the operating system and execute Python commands and scripts. It provides a text-based interface for entering commands and receiving output, making it a fundamental tool for running Python code.
An editor

Erklärung
An editor is not the correct choice in this context. While an editor can be used to write and edit Python scripts, it does not provide the functionality of a command-line interpreter to directly interact with the OS and execute Python commands. An editor is primarily used for writing and editing code, not for executing commands.
A compiler

Erklärung
A compiler is not the correct choice for this question. A compiler is a tool that translates source code into machine code or another form of code, but it does not provide the interactive command-line interface needed to interact with the OS and execute Python commands and scripts. A compiler is used to convert code into an executable form, not for direct interaction with the OS.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 140
Übersprungen
Q425

What is the default value of encoding in the string function encode()?



ascii
Erklärung
The encoding value ascii is not the default value in the string function encode(). While ascii encoding is limited to 128 characters and is commonly used for encoding English text, it is not the default encoding in this context.

qwerty
Erklärung
The encoding value qwerty is not a valid encoding option and is not the default value in the string function encode(). This choice is incorrect as it does not represent a recognized encoding format.

Richtige Antwort
utf-8
Erklärung
The default encoding value in the string function encode() is utf-8. This encoding is widely used and supports a wide range of characters, making it a common choice for encoding text data.

utf-16
Erklärung
The encoding value utf-16 is not the default value in the string function encode(). While utf-16 is a Unicode encoding that supports a larger range of characters compared to ascii, it is not the default encoding used in this specific function.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 147
Übersprungen
Q656

Which of the following statements are true?



(Select two answers)


Richtige Auswahl
The return keyword forces the function's execution to terminate

The return keyword forces the function to start its execution

Richtige Auswahl
The return keyword may cause the function to return a value
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 157
Übersprungen
Q644

A value returned by the input() function is:



Richtige Antwort
a string
Erklärung
The input() function in Python always returns a string, regardless of the type of input provided by the user. This is because Python treats all user inputs as strings by default, and it is up to the programmer to convert the input to the desired data type if needed.

a float
Erklärung
While the input() function can accept numerical input, it always returns the input as a string. If the user enters a numerical value, it will still be stored as a string. If you need to use the input as a float, you would need to explicitly convert it using the float() function.

an integer
Erklärung
Even if the user enters a whole number as input, the input() function will still return it as a string. If you need to use the input as an integer, you would need to convert it using the int() function after receiving the input as a string.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 161
Übersprungen
Q166

What is true about tuples?

(Select two answers.)

Richtige Auswahl
Tuples can be indexed and sliced like lists.
Erklärung
Similar to lists, tuples in Python can be indexed and sliced using square brackets. This allows for accessing specific elements within a tuple or extracting subsets of data from a tuple.

Richtige Auswahl
Tuples are immutable, which means that their contents cannot be changed during their lifetime.

Erklärung
Tuples are immutable data structures in Python, meaning that once they are created, their contents cannot be modified or changed. This immutability makes tuples suitable for storing fixed data that should not be altered.

The len() function cannot be applied to tuples.
Erklärung
The len() function can indeed be applied to tuples in Python. It returns the number of elements in the tuple, allowing for easy determination of the tuple's size or length.

An empty tuple is written as { }
Erklärung
An empty tuple in Python is denoted by a pair of parentheses with no elements inside, like this: (). Using curly braces { } would create an empty dictionary, not a tuple.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Which of the following functions can be invoked with two arguments?

Richtige Antwort
def iota(level, size=0):
    pass
Erklärung
The function `iota` can be invoked with two arguments because it has a parameter `level` that is required and a parameter `size` that has a default value of 0, making it optional to provide a second argument.
def lambda():
    pass
Erklärung
The function `lambda` does not have any parameters defined in its signature, so it cannot be invoked with any arguments.
def kappa(level):
    pass
Erklärung
The function `kappa` can only be invoked with one argument `level` as it does not have any other parameters defined in its signature.
def mu(Nonc):
    pass
Erklärung
The function `mu` can only be invoked with one argument `Nonc` as it does not have any other parameters defined in its signature.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 164
Übersprungen
Q150

Assuming that the tuple is a correctly created tuple,

the fact that tuples are immutable means that the following instruction:



my_tuple[1] = my_tuple[1] + my_tuple[0] 
---------------------------------------

is fully correct

Richtige Antwort
is illegal

can be executed if and only if the tuple contains at least two elements

may be illegal if the tuple contains strings
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 167
Übersprungen
Q332

By which variable of the sys module can we access command line arguments?



argsv

Richtige Antwort
argv

arguments

args
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 169
Übersprungen
Q205

Which of the following statements is false?



The right argument of the % operator can not be zero.

Richtige Antwort
The result of the / operator is always an integer value.

Multiplication precedes addition.

The ** operator has right-to-left associativity.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 172
Übersprungen
Q242

The += operator, when applied to strings, performs:



Richtige Antwort
Concatenation

Multiplication

Subtraction
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 173
Übersprungen
Q643

What is the expected behavior of the following program?



prin("Goodbye!")


The program will output ("Goodbye!")

Richtige Antwort
The program will generate an error message on the screen

The program will output Goodbye!

The program will output "Goodbye!"
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 177
Übersprungen
Q558

Which of the following statements can be used
to return the length of the given string str?



Richtige Antwort
len(str)

Erklärung
The `len()` function in Python is used to return the length of an object, such as a string. Therefore, `len(str)` is the correct choice to return the length of the given string `str`.
str.size()

Erklärung
The `size()` method is not a valid method for strings in Python. Therefore, `str.size()` is not the correct way to return the length of the given string `str`.
size(str)

Erklärung
There is no built-in `size()` function in Python to return the length of a string. Therefore, `size(str)` is not a valid choice for returning the length of the given string `str`.
str._len_()

Erklärung
The `_len_()` method is not a valid method for getting the length of a string in Python. Therefore, `str._len_()` is not the correct choice for returning the length of the given string `str`.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 179
Übersprungen
Q447

The None keyword designates:



a function which doesn't return a value

Richtige Antwort
a None value

an empty instruction
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 180
Übersprungen
Q171

A set of rules which defines the ways in which words can be coupled in sentences is called:

Richtige Antwort
syntax
Erklärung
Syntax refers to the set of rules that govern the structure of sentences in a language, including word order, punctuation, and grammar rules. It defines how words can be combined to form meaningful sentences, making it the correct choice in this context.

semantics
Erklärung
Semantics refers to the meaning of words and sentences in a language. While semantics is crucial for understanding the meaning of language, it does not specifically address the rules for combining words in sentences, making it an incorrect choice in this context.

dictionary
Erklärung
A dictionary is a reference book that provides definitions of words in a language. While dictionaries are essential for understanding the meanings of words, they do not define the rules for combining words in sentences, making it an incorrect choice in this context.

lexis
Erklärung
Lexis refers to the vocabulary or words used in a language. While vocabulary is an important aspect of language, it does not specifically define the rules for combining words in sentences, making it an incorrect choice in this context.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 181
Übersprungen
Q139

The digraph written as #! is used to:



make a particular module entity a private one.

Erklärung
The digraph #! is not used to make a particular module entity a private one in Python. In Python, the convention for making an entity private is by prefixing its name with an underscore, such as _my_private_module.
Richtige Antwort
tell a Unix or Unix-like OS how to execute the contents of a Python file.

Erklärung
The digraph #! is known as a shebang or hashbang and is used to tell a Unix or Unix-like operating system how to execute the contents of a Python file. It specifies the path to the Python interpreter that should be used to run the script.
tell an MS Windows OS how to execute the contents of a Python file.

Erklärung
The digraph #! is not used to tell a Microsoft Windows operating system how to execute the contents of a Python file. Windows uses file associations to determine how to execute files based on their extensions, such as .py for Python files.
create a docstring.

Erklärung
The digraph #! is not used to create a docstring in Python. Docstrings in Python are created using triple quotes (''' or """ """" "and are used to provide documentation for modules, classes, functions, or methods."
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 183
Übersprungen
Q339

You develop a Python application for your company.

You want to add notes to your code so other team members will understand it.



What should you do?



Richtige Antwort
Place the notes after the # sign on any line.

Place the notes before the first line of code separated by a blank line.

Place the notes after the last line of code separated by a blank line.

Place the notes inside of parentheses on any line.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 184
Übersprungen
Q164

What will happen when you attempt to run the following code?



print(Hello, World!)


The code will raise the ValueError exception.
Erklärung
The code will not raise a ValueError exception as there are no value-related issues in the code.

The code will raise the AttributeError exception.
Erklärung
The code will not raise an AttributeError exception as there are no attributes being accessed in the code.

The code will print Hello, World! to the console.
Erklärung
The code will not print "Hello, World!" to the console because it contains a syntax error and will not execute successfully.

Richtige Antwort
The code will raise the SyntaxError exception.
Erklärung
The code will raise a SyntaxError exception because the string "Hello, World!" is not enclosed in quotation marks, which is required in Python to denote a string literal.

The code will raise the TypeError exception.
Erklärung
The code will not raise a TypeError exception as there are no type-related issues in the code.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 186
Übersprungen
Q154

A function definition starts with the keyword:



function

Erklärung
The keyword "function" is also not a valid keyword in Python for defining functions. Python uses the keyword "def" specifically for function definitions. Attempting to use "function" instead of "def" will lead to a syntax error and the function will not be recognized by the interpreter.

Richtige Antwort
def
Erklärung
The keyword "def" is used in Python to define a function. It is a mandatory keyword that must be used at the beginning of a function definition to indicate the start of the function block. Without using "def", the interpreter will not recognize the following code as a function definition.

fun
Erklärung
The keyword "fun" is not a valid keyword in Python for defining functions. In Python, the correct keyword to start a function definition is "def". Using "fun" instead of "def" will result in a syntax error and the function will not be defined properly.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 194
Übersprungen
Q555

Which of the following lines properly starts a parameterless function definition?



Richtige Antwort
def fun():

function fun():

def fun:

fun function():
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 195
Übersprungen
Q323

The ** operator ...



does not exist.

performs floating-point multiplication.

performs duplicated multiplication.

Richtige Antwort
performs exponentiation.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 196
Übersprungen
Q158

Strings in Python are delimited with:



backslashes (i.e., \)

dollar symbol (i.e., $)

asterisks (i.e., *)

Richtige Antwort
double quotes (i.e., ") or single quotes (i.e., ')
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 197
Übersprungen
Q659

Which one of the lines should you put in the snippet below

to match the expected output?



Expected output:

[1, 2, 4, 7]


Code:

list = [2, 7, 1, 4]
 
# enter code here
 
print(list)


list.sorted()
Erklärung
The choice `list.sorted()` is incorrect because there is no method called `sorted()` for lists in Python. The correct method to sort a list in place is `sort()`.

Richtige Antwort
list.sort()
Erklärung
The correct choice is to use `list.sort()` as it sorts the elements of the list in place, which means the original list is modified. This will rearrange the elements in ascending order, resulting in the expected output [1, 2, 4, 7].

sort(list)
Erklärung
The choice `sort(list)` is incorrect because the `sort()` function is a method of the list class in Python and should be called on the list object directly, as in `list.sort()`.

sorted(list)
Erklärung
The choice `sorted(list)` is incorrect because the `sorted()` function returns a new sorted list without modifying the original list. In this case, we want to sort the original list in place, so `list.sort()` is the correct choice.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 198
Übersprungen
Q247

Which of the following variable names are illegal and will cause the SyntaxError exception?



(Select two answers)



Richtige Auswahl
for

Richtige Auswahl
in

print

In
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 200
Übersprungen
Q545

What is IDLE?



A version of Python

Erklärung
This choice is incorrect as IDLE is not a version of Python. It is a separate software tool that comes bundled with the Python programming language distribution, serving as an interactive environment for Python development and learning.

Richtige Antwort
An acronym that stands for Integrated Development and Learning Environment for Python

Erklärung
IDLE is an acronym that stands for Integrated Development and Learning Environment for Python. It is an integrated development environment (IDE) specifically designed for Python programming, providing features such as code editing, debugging, and interactive Python shell.

An acronym that stands for Interactive Development and Learning Extension
Erklärung
This choice is incorrect as IDLE does not stand for Interactive Development and Learning Extension. IDLE is specifically tailored for Python development and learning, offering a range of tools and features to support Python programmers.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 202
Übersprungen
Q416
Consider the following code.

x = [0, 1, 2]
x[0], x[2] = x[2], x[0]

What does the second assignment do?

Richtige Antwort
It reverses the list.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 206
Übersprungen
Q146
What are the four fundamental elements that make a language?

Richtige Antwort
An alphabet, a lexis, a syntax, and semantics
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 208
Übersprungen
Q149
Which of the following statements are true?
(Select two answers)

Richtige Auswahl
The ** operator uses right-sided binding.
Erklärung
The ** operator in Python uses right-sided binding, meaning that when there are multiple ** operators in an expression, the rightmost one is evaluated first. This is important to consider when working with exponentiation operations in Python.

Richtige Auswahl
The right argument of the % operator cannot be zero.
Erklärung
In Python, when using the % operator for the modulo operation, the right argument (the divisor) cannot be zero. Attempting to perform modulo division by zero will result in a ZeroDivisionError.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 213
Übersprungen
Q144
What do you call a tool that lets you lanch your code step-by-step and inspect it at each moment of execution?

Richtige Antwort
A debugger

Erklärung
A debugger is the correct choice because it is a tool specifically designed to help developers launch their code step-by-step and inspect it at each moment of execution. 
Debuggers allow for setting breakpoints, viewing variable values, and tracking the flow of the code during execution, making it an essential tool for troubleshooting and understanding code behavior.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 217
Übersprungen
Q344
Which one of the following is an example of a Python file extension?

Richtige Antwort
py

Erklärung
The ".py" file extension is the standard file extension used for Python files. It indicates that the file contains Python code and should be interpreted by the Python interpreter. 
This extension is widely recognized and used in the Python programming community.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 218
Übersprungen
Q245
What do you call a file containing a program written in a high-level programming language?

Richtige Antwort
A source file

Erklärung
A source file is the correct term for a file containing a program written in a high-level programming language. It typically contains human-readable code that needs to be translated or compiled into machine code for execution.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 229
Übersprungen
Q347
The most important difference between integer and floating-point numbers lies in the fact that:

Richtige Antwort
they are stored differently in the computer memory

Erklärung
Integer and floating-point numbers are stored differently in computer memory due to their distinct data types and representations. 
Integers are typically stored as whole numbers without decimal points, while floating-point numbers are stored with a decimal point and can represent fractional values. 
This difference in storage affects how arithmetic operations are performed on these types of numbers.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 230
Übersprungen
Q646

The \n digraph forces the print() function to?

Richtige Antwort
break the output line

Erklärung
The \n digraph in Python is known as the newline character, which is used to insert a line break in the output. When encountered in a string within the print() function, it forces the output to break to a new line, making it the correct choice.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 232
Übersprungen
Q543
What is CPython?

Richtige Antwort
The default implementation of the Python programming language

Erklärung
CPython is indeed the default and most widely used implementation of the Python programming language. It is written in C and is known for its simplicity and ease of use, making it the go-to choice for many Python developers.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Frage 239
Übersprungen
Q167
Python is an example of which programming language category?

Richtige Antwort
interpreted

Erklärung
Python is categorized as an interpreted programming language, meaning that the source code is executed line by line by an interpreter at runtime without the need for a separate compilation step.

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
"""