"""

Q246

What is the best definition of a script?



It's an error message generated by the interpreter

Richtige Antwort
It's a text file that contains instructions which make up a Python program

It's a text file that contains sequences of zeroes and ones

It's an error message generated by the compiler
"""